import{Matrix3 as t,Vector3 as e,Color as n}from"three";class PLYExporter{parse(i,r,l={}){function o(t){i.traverse(function(e){if(!0===e.isMesh||e.isPoints){let n=e,i=n.geometry;!0===i.hasAttribute("position")&&t(n,i)}})}let a=(l=Object.assign({binary:!1,excludeAttributes:[],littleEndian:!1},l)).excludeAttributes,u=!0,f=!1,s=!1,$=!1,d=0,p=0;i.traverse(function(t){if(!0===t.isMesh){let e=t.geometry,n=e.getAttribute("position"),i=e.getAttribute("normal"),r=e.getAttribute("uv"),l=e.getAttribute("color"),o=e.getIndex();void 0!==n&&(d+=n.count,p+=o?o.count/3:n.count/3,void 0!==i&&(f=!0),void 0!==r&&($=!0),void 0!==l&&(s=!0))}else if(t.isPoints){let a=t.geometry,g=a.getAttribute("position"),c=a.getAttribute("normal"),b=a.getAttribute("color");d+=g.count,void 0!==c&&(f=!0),void 0!==b&&(s=!0),u=!1}});let g=new n;if(u=u&&-1===a.indexOf("index"),f=f&&-1===a.indexOf("normal"),s=s&&-1===a.indexOf("color"),$=$&&-1===a.indexOf("uv"),u&&p!==Math.floor(p))return console.error("PLYExporter: Failed to generate a valid PLY file with triangle indices because the number of indices is not divisible by 3."),null;let c=`ply
format ${l.binary?l.littleEndian?"binary_little_endian":"binary_big_endian":"ascii"} 1.0
element vertex ${d}
property float x
property float y
property float z
`;!0===f&&(c+="property float nx\nproperty float ny\nproperty float nz\n"),!0===$&&(c+="property float s\nproperty float t\n"),!0===s&&(c+="property uchar red\nproperty uchar green\nproperty uchar blue\n"),!0===u&&(c+=`element face ${p}
property list uchar int vertex_index
`),c+="end_header\n";let b=new e,x=new t,y=null;if(!0===l.binary){let m=new TextEncoder().encode(c),_=d*(12+(f?12:0)+(s?3:0)+($?8:0)),A=u?13*p:0,E=new DataView(new ArrayBuffer(m.length+_+A));new Uint8Array(E.buffer).set(m,0);let v=m.length,h=m.length+_,F=0;o(function(t,e){let n=e.getAttribute("position"),i=e.getAttribute("normal"),r=e.getAttribute("uv"),o=e.getAttribute("color"),a=e.getIndex();x.getNormalMatrix(t.matrixWorld);for(let d=0,p=n.count;d<p;d++)b.fromBufferAttribute(n,d),b.applyMatrix4(t.matrixWorld),E.setFloat32(v,b.x,l.littleEndian),v+=4,E.setFloat32(v,b.y,l.littleEndian),v+=4,E.setFloat32(v,b.z,l.littleEndian),v+=4,!0===f&&(null!=i?(b.fromBufferAttribute(i,d),b.applyMatrix3(x).normalize(),E.setFloat32(v,b.x,l.littleEndian),v+=4,E.setFloat32(v,b.y,l.littleEndian),v+=4,E.setFloat32(v,b.z,l.littleEndian),v+=4):(E.setFloat32(v,0,l.littleEndian),v+=4,E.setFloat32(v,0,l.littleEndian),v+=4,E.setFloat32(v,0,l.littleEndian),v+=4)),!0===$&&(null!=r?(E.setFloat32(v,r.getX(d),l.littleEndian),v+=4,E.setFloat32(v,r.getY(d),l.littleEndian),v+=4):(E.setFloat32(v,0,l.littleEndian),v+=4,E.setFloat32(v,0,l.littleEndian),v+=4)),!0===s&&(null!=o?(g.fromBufferAttribute(o,d).convertLinearToSRGB(),E.setUint8(v,Math.floor(255*g.r)),v+=1,E.setUint8(v,Math.floor(255*g.g)),v+=1,E.setUint8(v,Math.floor(255*g.b)),v+=1):(E.setUint8(v,255),v+=1,E.setUint8(v,255),v+=1,E.setUint8(v,255),v+=1));if(!0===u){if(null!==a)for(let c=0,y=a.count;c<y;c+=3)E.setUint8(h,3),h+=1,E.setUint32(h,a.getX(c+0)+F,l.littleEndian),h+=4,E.setUint32(h,a.getX(c+1)+F,l.littleEndian),h+=4,E.setUint32(h,a.getX(c+2)+F,l.littleEndian),h+=4;else for(let m=0,_=n.count;m<_;m+=3)E.setUint8(h,3),h+=1,E.setUint32(h,F+m,l.littleEndian),h+=4,E.setUint32(h,F+m+1,l.littleEndian),h+=4,E.setUint32(h,F+m+2,l.littleEndian),h+=4}F+=n.count}),y=E.buffer}else{let U=0,M="",w="";o(function(t,e){let n=e.getAttribute("position"),i=e.getAttribute("normal"),r=e.getAttribute("uv"),l=e.getAttribute("color"),o=e.getIndex();x.getNormalMatrix(t.matrixWorld);for(let a=0,d=n.count;a<d;a++){b.fromBufferAttribute(n,a),b.applyMatrix4(t.matrixWorld);let c=b.x+" "+b.y+" "+b.z;!0===f&&(null!=i?(b.fromBufferAttribute(i,a),b.applyMatrix3(x).normalize(),c+=" "+b.x+" "+b.y+" "+b.z):c+=" 0 0 0"),!0===$&&(null!=r?c+=" "+r.getX(a)+" "+r.getY(a):c+=" 0 0"),!0===s&&(null!=l?(g.fromBufferAttribute(l,a).convertLinearToSRGB(),c+=" "+Math.floor(255*g.r)+" "+Math.floor(255*g.g)+" "+Math.floor(255*g.b)):c+=" 255 255 255"),M+=c+"\n"}if(!0===u){if(null!==o)for(let y=0,m=o.count;y<m;y+=3)w+=`3 ${o.getX(y+0)+U}`,w+=` ${o.getX(y+1)+U}`,w+=` ${o.getX(y+2)+U}
`;else for(let _=0,A=n.count;_<A;_+=3)w+=`3 ${U+_} ${U+_+1} ${U+_+2}
`;p+=o?o.count/3:n.count/3}U+=n.count}),y=`${c}${M}${u?`${w}
`:"\n"}`}return"function"==typeof r&&requestAnimationFrame(()=>r(y)),y}}export{PLYExporter};